name: streamed_file_uploader_example
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  streamed_file_uploader:
    path: ..

dev_dependencies:
  lint: ^2.8.0

flutter:
  uses-material-design: true
