name: file_streamer_example
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.11.4

dependencies:
  file_streamer:
    path: ..
  flutter:
    sdk: flutter
  http: ^1.6.0

dev_dependencies:
  lint: ^2.8.0

flutter:
  uses-material-design: true
