name: file_streamer
description: A zero-retention, stream-first file access library for Dart & Flutter.

version: 0.1.0

repository: https://github.com/minhqdao/file_streamer
homepage: https://github.com/minhqdao/file_streamer
issue_tracker: https://github.com/minhqdao/file_streamer/issues

topics:
  - read
  - load
  - upload
  - stream
  - wasm

environment:
  sdk: "^3.6.0"

dependencies:
  file_picker: ^11.0.2
  mime: ^2.0.0
  web: ^1.1.1

dev_dependencies:
  lint: ^2.8.0
  path: ^1.9.1
  test: ^1.31.0
