name: CI
on: push

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: dart-lang/setup-dart@v1
            - name: Remove Flutter deps to run formatter in a pure Dart environment
              run: sed -i '/file_picker:/d' pubspec.yaml
            - run: dart pub get --no-example
            - run: |
                  dart format .
                  git diff example/flutter/lib/main.dart

    analyze:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: dart-lang/setup-dart@v1
            - uses: subosito/flutter-action@v2
            - run: dart pub get --no-example
            - name: Exclude example for CI
              run: echo -e "\nanalyzer:\n  exclude:\n    - \"example/**\"" >> analysis_options.yaml
            - run: dart analyze --fatal-infos --fatal-warnings

    test:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v6
            - uses: dart-lang/setup-dart@v1
            - uses: subosito/flutter-action@v2
            - run: dart pub get --no-example
            - run: dart test

    test-cli:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: dart-lang/setup-dart@v1
            - name: Remove Flutter deps to simulate a pure Dart environment
              run: sed -i '/file_picker:/d' pubspec.yaml
            - run: dart pub get --no-example
            - run: dart test test/file_streamer_cli_test.dart

    test-chrome:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: dart-lang/setup-dart@v1
            - uses: subosito/flutter-action@v2
            - run: dart pub get --no-example
            - run: dart test -p chrome
